// https://www.bscscan.com/address/0x1e70972ec6c8a3fae3ac34c9f3818ec46eb3bd5d#code
// SPDX-License-Identifier: UNLICENSED
// !! THIS FILE WAS AUTOGENERATED BY abi-to-sol v0.8.0. SEE SOURCE BELOW. !!
pragma solidity >=0.7.0 <0.9.0;

interface IFriend3V1 {
    event OwnershipTransferred(
        address indexed previousOwner,
        address indexed newOwner
    );
    event Trade(
        address trader,
        address subject,
        bool isBuy,
        uint256 ticketAmount,
        uint256 ethAmount,
        uint256 protocolEthAmount,
        uint256 subjectEthAmount,
        uint256 supply
    );

    function buyTickets(
        address ticketsSubject,
        uint256 amount
    ) external payable;

    function getBuyPrice(
        address ticketsSubject,
        uint256 amount
    ) external view returns (uint256);

    function getBuyPriceAfterFee(
        address ticketsSubject,
        uint256 amount
    ) external view returns (uint256);

    function getPrice(
        uint256 supply,
        uint256 amount
    ) external pure returns (uint256);

    function getSellPrice(
        address ticketsSubject,
        uint256 amount
    ) external view returns (uint256);

    function getSellPriceAfterFee(
        address ticketsSubject,
        uint256 amount
    ) external view returns (uint256);

    function owner() external view returns (address);

    function protocolFeeDestination() external view returns (address);

    function protocolFeePercent() external view returns (uint256);

    function renounceOwnership() external;

    function sellTickets(
        address ticketsSubject,
        uint256 amount
    ) external payable;

    function setFeeDestination(address _feeDestination) external;

    function setProtocolFeePercent(uint256 _feePercent) external;

    function setSubjectFeePercent(uint256 _feePercent) external;

    function subjectFeePercent() external view returns (uint256);

    function ticketsBalance(address, address) external view returns (uint256);

    function ticketsSupply(address) external view returns (uint256);

    function transferOwnership(address newOwner) external;
}
